### PR TITLE
warpaltarpers

### PR DESCRIPTION
**Pull request by warpaltarpers**
Added a circular button widget based off of the design principles for "[neumorphism](https://uxdesign.cc/neumorphism-in-user-interfaces-b47cef3bf3a6)".

Shadows are working a little weird on my Android emulator, but should display fine on a physical device; I can fix it if not! Most changes to `lib\Screens\home_page.dart` were changes from my editor's auto-formatter.

- [X] I have read the Code Of Conduct.
- [X] I have followed all the steps of submission properly.

_Found when searching for repos to contribute to for Hacktoberfest 2021 via issue #1._

### CODE REVIEW

**Comment by RushiDonga** [comment]
Hey @warpaltarpers, that was really an awesome piece of creativity.

You can also share your contribution on social media and tag us [@club_gamma](https://www.instagram.com/club_gamma/)

**Comment by warpaltarpers** [comment]
Thank you @RushiDonga! I'll be sure to make a post on social media as soon as I can!

**Comment by RushiDonga** [comment]
Hii @warpaltarpers,

Can you help us solve this [Issue](https://github.com/clubgamma/gamma_notes/issues/6) Or can you tag someone who can help us with this Issue.

Your efforts will be appreciated :)

Thank You ❤

**Comment by warpaltarpers** [comment]
I will take a look at it and see if there's anything I can do!

**Comment by RushiDonga** [comment]
Ya, that will be great !!

**Pull request merged**
